INSERT INTO bookmarks (title, url, created_at) VALUES ('How To Remove Docker Containers, Images, Volumes, and Networks', 'https://linuxize.com/post/how-to-remove-docker-images-containers-volumes-and-networks', CURRENT_TIMESTAMP),
('postgre test All You Need To Know About Unit Testing with Spring Boot', 'https://reflectoring.io/unit-testing-spring-boot', CURRENT_TIMESTAMP),
('postgre testSpring Boot Security Jwt Authentication', 'https://www.devglan.com/spring-security/spring-boot-jwt-auth', CURRENT_TIMESTAMP),
('postgre testA categorized list of all Java and JVM features since JDK 8', 'https://advancedweb.hu/2019/02/19/post_java_8', CURRENT_TIMESTAMP),
('postgre testFlyway and jOOQ for Unbeatable SQL Development Productivity', 'https://blog.jooq.org/2014/06/25/flyway-and-jooq-for-unbeatable-sql-development-productivity', CURRENT_TIMESTAMP),
('postgre testJava Microservices: A Practical Guide', 'https://www.marcobehler.com/guides/java-microservices-a-practical-guide', CURRENT_TIMESTAMP),
('postgre testSpring Boot integration with p6spy, datasource-proxy, flexy-pool and spring-cloud-sleuth', 'https://github.com/gavlyukovskiy/spring-boot-data-source-decorator', CURRENT_TIMESTAMP),
('postgre testBuild a JavaScript Command Line Interface (CLI) with Node.js', 'https://www.sitepoint.com/javascript-command-line-interface-cli-node-js', CURRENT_TIMESTAMP),
('postgre testHow to teach Git', 'https://rachelcarmena.github.io/2018/12/12/how-to-teach-git.html', CURRENT_TIMESTAMP),
('postgre testAchieving framework-independent zen with the power of interfaces and hexagonal architecture', 'https://rskupnik.github.io/framework-independence-with-hexagonal-architecture', CURRENT_TIMESTAMP),
('postgre testDeserialize Immutable Objects with Jackson', 'https://www.baeldung.com/jackson-deserialize-immutable-objects', CURRENT_TIMESTAMP),
('postgre testSpringBoot Integration Testing using TestContainers Starter', 'https://sivalabs.in/2020/02/spring-boot-integration-testing-using-testcontainers-starter', CURRENT_TIMESTAMP);